function [output] = generateLinearChirpSignal(initial_frequency, bandwidth, phase, amplitude, samplingFrequency, duration)

timeVector = (0:duration*samplingFrequency) / samplingFrequency;

output = amplitude * ...
    cos(2*pi * ...
    (initial_frequency*timeVector + bandwidth .* timeVector.^2) ...
    + phase);